name: Benchmark CI

on:
  push:
    branches:
      - benchmark
  workflow_dispatch:

jobs:
  run-racket-test-and-copy-json-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cache Racket dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-racket-8.1
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.14
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'current'
      - name: Install Dependencies
        run: raco pkg install --auto --skip-installed roulette-lib/ roulette/ benchmark_ci/

      
      - name: Link benchmark hashlang
        run: |
          raco link benchmark_ci

      - name: Run benchmarks
        run: ./run_benchmarks.sh

      - name: Clone target repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone https://github.com/neuppl/roulette-bench-data.git
        
      - name: log 
        run: |
          echo "Current directory: $(pwd)"
          echo "Output of ls: $(ls -la)"

      - name: Copy files
        run: ./copy_results.sh

          
      - name: Commit and push changes
        run: |
          cd roulette-benchmark-data
          git add .
          git commit -m "push benchmark results"
          git push

