name: Benchmark CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-racket-test-and-copy-json-output:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      
      - name: Link benchmark hashlang
        run: |
          raco link roulette/benchmark_ci
      
      - name: Install Racket Dependencies
        run: |
          raco pkg install relation-lib json make-log-interceptor 

      - name: Run benchmarks
        run: ./run_benchmarks.sh

      - name: Clone target repo
        run: |
          git clone git@github.com:Smaran-Teja/roulette-benchmark-data.git
        
      - name: log 
        run: |
          echo "Current directory: $(pwd)"
          echo "Output of ls: $(ls -la)"

      - name: Copy files
        run: ./copy_results.sh

          
      - name: Commit and push changes
        run: |
          cd roulette-benchmark-data
          git add .
          git commit -m "push benchmark results"
          git push

