name: Benchmark CI

on:
  push:
    branches:
      - benchmark
  workflow_dispatch:

jobs:
  run-racket-test-and-copy-json-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.14
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'current'

      - name: Install Dependencies
        run: raco pkg install --auto --skip-installed roulette-lib/ roulette/ benchmark_ci/
      
      - name: Link benchmark hashlang
        run: |
          raco link benchmark_ci

      - name: Run benchmarks
        run: ./run_benchmarks.sh

      - uses: actions/checkout@v4
        with:
          repository: 'neuppl/roulette-bench-data'
          path: 'roulette-bench-data'  # This will be a subdirectory
          token: ${{ secrets.PAT }}  # MUST use PAT for push permissions
          persist-credentials: true  # Keep credentials for push
        
      - name: log 
        run: |
          echo "Current directory: $(pwd)"
          echo "Output of ls: $(ls -la)"

      - name: Copy files
        run: ./copy_results.sh

          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cd roulette-bench-data
          git add .
          git commit -m "push benchmark results"
          git push

